bot_token: 1217183416:AAGguh1XmBhKmTjUB_a3spM5rVSzMDAMLvw
preview_text: 0
update_interval: 1
error_threshold: 100
mysql:
  host: database-1.crn2x85tf67q.ap-northeast-1.rds.amazonaws.com
  port: 3306
  user: makubex800211@gmail.com
  password: Qw52105210
  database: database-1
